#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_getpid  4
#define SYS_exec    5
#define SYS_close   6
#define SYS_open    7
#define SYS_read    8
#define SYS_write   9
#define SYS_chdir   10
#define SYS_makenode 11
#define SYS_duplicate 12
#define SYS_sbrk      13
#define SYS_uptime    14
#define SYS_mkdir     15
#define SYS_unlink    16
#define SYS_crash_arm 17