# system calls
print "",".globl fork\n";
print "",".globl exit\n";
print "",".globl wait\n";
print "",".globl getpid\n";
print "",".globl exec\n";
print "",".globl open\n";
print "",".globl close\n";
print "",".globl read\n";
print "",".globl write\n";
print "",".globl chdir\n";
print "",".globl makenode\n";
print "",".globl duplicate\n";
print "",".globl sbrk\n";
print "",".globl uptime\n";
print "", ".globl mkdir\n";
print "", ".globl unlink\n";
#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"../kernel/sys/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("getpid");
entry("close");
entry("open");
entry("exec");
entry("read");
entry("write");
entry("chdir");
entry("makenode");
entry("duplicate");
entry("sbrk");
entry("uptime");
entry("mkdir");
entry("unlink");